{% set name = "threadom" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/threadom-{{ version }}.tar.gz
  sha256: fdc0b287aa0c0da8dd50c2f07424aaa58b6fd9d36085bd79c7fa4da31d9a9c4f

build:
  entry_points:
    - threadom = threadom.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - threadom
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyrustic/threadom
  summary: Tkinter-compatible multithreading
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
